name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 23 * * 6'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          # - "macos-latest"
          # - "windows-latest"
        node_version:
          - '20'
          # - "18"
          # - "16"
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Dependencies
        run: yarn

      - name: Run Test
        run: yarn build

      - name: Check File Changes
        run: echo "Listing changed files:" && git diff --name-only --exit-code && echo "No files changed."

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint
